#!/usr/bin/env python3
"""
Generate Colors.qml for ii-sddm-theme from Caelestia's color scheme.
This script converts Caelestia's Material You colors to the QML format expected by ii-sddm-theme.
"""

import json
import sys
from pathlib import Path


def hex_to_qml_color(hex_color: str) -> str:
    """Convert hex color (without #) to QML color format."""
    return f'"#{hex_color}"'


def generate_colors_qml(scheme_data: dict) -> str:
    """Generate Colors.qml content from Caelestia scheme data."""
    colors = scheme_data.get("colours", {})
    
    # Map Caelestia color names to Material You names
    color_mapping = {
        "background": "background",
        "onBackground": "on_background",
        "surface": "surface",
        "surfaceDim": "surface_dim",
        "surfaceBright": "surface_bright",
        "surfaceContainerLowest": "surface_container_lowest",
        "surfaceContainerLow": "surface_container_low",
        "surfaceContainer": "surface_container",
        "surfaceContainerHigh": "surface_container_high",
        "surfaceContainerHighest": "surface_container_highest",
        "onSurface": "on_surface",
        "surfaceVariant": "surface_variant",
        "onSurfaceVariant": "on_surface_variant",
        "inverseSurface": "inverse_surface",
        "inverseOnSurface": "inverse_on_surface",
        "outline": "outline",
        "outlineVariant": "outline_variant",
        "shadow": "shadow",
        "scrim": "scrim",
        "surfaceTint": "surface_tint",
        "primary": "primary",
        "onPrimary": "on_primary",
        "primaryContainer": "primary_container",
        "onPrimaryContainer": "on_primary_container",
        "inversePrimary": "inverse_primary",
        "secondary": "secondary",
        "onSecondary": "on_secondary",
        "secondaryContainer": "secondary_container",
        "onSecondaryContainer": "on_secondary_container",
        "tertiary": "tertiary",
        "onTertiary": "on_tertiary",
        "tertiaryContainer": "tertiary_container",
        "onTertiaryContainer": "on_tertiary_container",
        "error": "error",
        "onError": "on_error",
        "errorContainer": "error_container",
        "onErrorContainer": "on_error_container",
        "primaryFixed": "primary_fixed",
        "primaryFixedDim": "primary_fixed_dim",
        "onPrimaryFixed": "on_primary_fixed",
        "onPrimaryFixedVariant": "on_primary_fixed_variant",
        "secondaryFixed": "secondary_fixed",
        "secondaryFixedDim": "secondary_fixed_dim",
        "onSecondaryFixed": "on_secondary_fixed",
        "onSecondaryFixedVariant": "on_secondary_fixed_variant",
        "tertiaryFixed": "tertiary_fixed",
        "tertiaryFixedDim": "tertiary_fixed_dim",
        "onTertiaryFixed": "on_tertiary_fixed",
        "onTertiaryFixedVariant": "on_tertiary_fixed_variant",
    }
    
    # Build the QML file
    qml_lines = [
        "import QtQuick",
        "pragma Singleton",
        "",
        "// Generated by Caelestia",
        "QtObject {",
        "    property real contentTransparency: 0.57",
        "    property real backgroundTransparency: 0",
    ]
    
    # Add color properties
    for caelestia_name, qml_name in color_mapping.items():
        if caelestia_name in colors:
            color_value = hex_to_qml_color(colors[caelestia_name])
            qml_lines.append(f"    property color {qml_name}: {color_value}")
    
    # Add derived color properties (from ii-sddm-theme)
    qml_lines.extend([
        "    property color colSubtext: outline",
        "    property color colLayer0: mix(transparentize(background, backgroundTransparency), primary, 0.99)",
        "    property color colOnLayer0: on_background",
        "    property color colLayer0Hover: transparentize(mix(colLayer0, colOnLayer0, 0.9), contentTransparency)",
        "    property color colLayer0Active: transparentize(mix(colLayer0, colOnLayer0, 0.8), contentTransparency)",
        "    property color colLayer0Border: mix(outline_variant, colLayer0, 0.4)",
        "    property color colLayer1: transparentize(surface_container_low, contentTransparency)",
        "    property color colOnLayer1: on_surface_variant",
        "    property color colOnLayer1Inactive: mix(colOnLayer1, colLayer1, 0.45)",
        "    property color colLayer2: transparentize(surface_container, contentTransparency)",
        "    property color colOnLayer2: on_surface",
        "    property color colOnLayer2Disabled: mix(colOnLayer2, background, 0.4)",
        "    property color colLayer1Hover: transparentize(mix(colLayer1, colOnLayer1, 0.92), contentTransparency)",
        "    property color colLayer1Active: transparentize(mix(colLayer1, colOnLayer1, 0.85), contentTransparency)",
        "    property color colLayer2Hover: transparentize(mix(colLayer2, colOnLayer2, 0.9), contentTransparency)",
        "    property color colLayer2Active: transparentize(mix(colLayer2, colOnLayer2, 0.8), contentTransparency)",
        "    property color colLayer2Disabled: transparentize(mix(colLayer2, background, 0.8), contentTransparency)",
        "    property color colLayer3: transparentize(surface_container_high, contentTransparency)",
        "    property color colOnLayer3: on_surface",
        "    property color colLayer3Hover: transparentize(mix(colLayer3, colOnLayer3, 0.9), contentTransparency)",
        "    property color colLayer3Active: transparentize(mix(colLayer3, colOnLayer3, 0.8), contentTransparency)",
        "    property color colLayer4: transparentize(surface_container_highest, contentTransparency)",
        "    property color colOnLayer4: on_surface",
        "    property color colLayer4Hover: transparentize(mix(colLayer4, colOnLayer4, 0.9), contentTransparency)",
        "    property color colLayer4Active: transparentize(mix(colLayer4, colOnLayer4, 0.8), contentTransparency)",
        "    property color colPrimary: primary",
        "    property color colOnPrimary: on_primary",
        "    property color colPrimaryHover: mix(colPrimary, colLayer1Hover, 0.87)",
        "    property color colPrimaryActive: mix(colPrimary, colLayer1Active, 0.7)",
        "    property color colPrimaryContainer: primary_container",
        "    property color colPrimaryContainerHover: mix(colPrimaryContainer, on_primary_container, 0.9)",
        "    property color colPrimaryContainerActive: mix(colPrimaryContainer, on_primary_container, 0.8)",
        "    property color colSecondary: secondary",
        "    property color colSecondaryHover: mix(secondary, colLayer1Hover, 0.85)",
        "    property color colSecondaryActive: mix(secondary, colLayer1Active, 0.4)",
        "    property color colSecondaryContainer: secondary_container",
        "    property color colSecondaryContainerHover: mix(secondary_container, on_secondary_container, 0.9)",
        "    property color colSecondaryContainerActive: mix(secondary_container, on_secondary_container, 0.54)",
        "    property color colTertiary: tertiary",
        "    property color colTertiaryHover: mix(tertiary, colLayer1Hover, 0.85)",
        "    property color colTertiaryActive: mix(tertiary, colLayer1Active, 0.4)",
        "    property color colTertiaryContainer: tertiary_container",
        "    property color colTertiaryContainerHover: mix(tertiary_container, on_tertiary_container, 0.9)",
        "    property color colTertiaryContainerActive: mix(tertiary_container, colLayer1Active, 0.54)",
        "    property color colSurfaceContainerLow: transparentize(surface_container_low, contentTransparency)",
        "    property color colSurfaceContainer: transparentize(surface_container, contentTransparency)",
        "    property color colSurfaceContainerHigh: transparentize(surface_container_high, contentTransparency)",
        "    property color colSurfaceContainerHighest: transparentize(surface_container_highest, contentTransparency)",
        "    property color colSurfaceContainerHighestHover: mix(surface_container_highest, on_surface, 0.95)",
        "    property color colSurfaceContainerHighestActive: mix(surface_container_highest, on_surface, 0.85)",
        "    property color colOnSurface: on_surface",
        "    property color colOnSurfaceVariant: on_surface_variant",
        "    property color colTooltip: inverse_surface",
        "    property color colOnTooltip: inverse_on_surface",
        "    property color colScrim: transparentize(scrim, 0.5)",
        "    property color colShadow: transparentize(shadow, 0.7)",
        "    property color colOutline: outline",
        "    property color colOutlineVariant: outline_variant",
        "    property color colError: error",
        "    property color colErrorHover: mix(error, colLayer1Hover, 0.85)",
        "    property color colErrorActive: mix(error, colLayer1Active, 0.7)",
        "    property color colOnError: on_error",
        "    property color colErrorContainer: error_container",
        "    property color colErrorContainerHover: mix(error_container, on_error_container, 0.9)",
        "    property color colErrorContainerActive: mix(error_container, on_error_container, 0.7)",
        "",
        "    function transparentize(color, percentage) {",
        "        if (percentage === undefined)",
        "            percentage = 1;",
        "",
        "        var c = Qt.color(color);",
        "        return Qt.rgba(c.r, c.g, c.b, c.a * (1 - percentage));",
        "    }",
        "",
        "    function mix(color1, color2, percentage) {",
        "        if (percentage === undefined)",
        "            percentage = 0.5;",
        "",
        "        var c1 = Qt.color(color1);",
        "        var c2 = Qt.color(color2);",
        "        return Qt.rgba(percentage * c1.r + (1 - percentage) * c2.r, percentage * c1.g + (1 - percentage) * c2.g, percentage * c1.b + (1 - percentage) * c2.b, percentage * c1.a + (1 - percentage) * c2.a);",
        "    }",
        "",
        "}",
    ])
    
    return "\n".join(qml_lines)


def main():
    # Read Caelestia scheme
    scheme_path = Path.home() / ".local/state/caelestia/scheme.json"
    
    if not scheme_path.exists():
        print(f"Error: Caelestia scheme not found at {scheme_path}", file=sys.stderr)
        sys.exit(1)
    
    try:
        with open(scheme_path, "r") as f:
            scheme_data = json.load(f)
    except (json.JSONDecodeError, IOError) as e:
        print(f"Error reading scheme: {e}", file=sys.stderr)
        sys.exit(1)
    
    # Generate QML
    qml_content = generate_colors_qml(scheme_data)
    
    # Output to stdout (will be redirected by the calling script)
    print(qml_content)


if __name__ == "__main__":
    main()
