#!/usr/bin/env python3
"""
Generate Settings.qml for ii-sddm-theme from user preferences.
This provides UI/behavior settings for the SDDM theme.
"""

import json
import sys
from pathlib import Path


def generate_settings_qml() -> str:
    """Generate Settings.qml content with sensible defaults."""

    # These are the settings matching the ii-sddm-theme Components/Settings.qml
    # You can customize these defaults as needed
    qml_content = """import QtQuick
pragma Singleton

// Generated by Caelestia - Customize these settings as needed
// On the comment on the right there are all possible options
QtObject {
    property string panelFamily: "ii" // "ii", "waffle"
    property string time_format: "h:mm ap" // "hh:mm","h:mm ap","h:mm AP"
    property string background_widgets_clock_styleLocked: "cookie" // "none", "digital", "cookie"
    property real background_widgets_clock_digital_font_roundness: 1.45
    property real background_widgets_clock_digital_font_size: 90
    property real background_widgets_clock_digital_font_weight: 350
    property real background_widgets_clock_digital_font_width: 100
    property bool background_widgets_clock_digital_showDate: true // true, false
    property bool background_widgets_clock_digital_vertical: false // true, false
    property bool background_widgets_clock_cookie_constantlyRotate: false // true, false
    property string background_widgets_clock_cookie_dateStyle: "bubble" // "hide", "rect", "bubble", "border"
    property string background_widgets_clock_cookie_dialNumberStyle: "full" // "full", "dots", "numbers", "none"
    property string background_widgets_clock_cookie_hourHandStyle: "hollow" // "fill", "hollow", "classic", "hide"
    property bool background_widgets_clock_cookie_hourMarks: false // true, false
    property string background_widgets_clock_cookie_minuteHandStyle: "thin" // "thin", "medium", "bold", "classic", "hide"
    property string background_widgets_clock_cookie_secondHandStyle: "line" // "dot", "classic", "line", "hide"
    property int background_widgets_clock_cookie_sides: 14 // 0 to i dont know what is the limit, i wouldn't go too high
    property bool background_widgets_clock_cookie_timeIndicators: true // true, false
    property string background_widgets_clock_quote_text: "Welcome to Caelestia" // "you can write anything you want"
    property bool background_widgets_clock_quote_enable: true // true, false
    property bool lock_blur_enable: false // true, false
    property bool lock_showLockedText: true // true, false
    property bool time_secondPrecision: true // true, false
    property bool lock_materialShapeChars: true // true, false
    property bool background_widgets_clock_digital_animateChange: true // true, false
    property bool background_widgets_clock_cookie_useSineCookie: false // true, false
}
"""

    return qml_content


def main():
    # Generate QML
    qml_content = generate_settings_qml()

    # Output to stdout (will be redirected by the calling script)
    print(qml_content)


if __name__ == "__main__":
    main()
